config_name: DefaultConfig
version: 0.1a
window_settings:
    api: GLFW # GLFW or WIN32
    name: Homework1
    width: 1920
    height: 1080
    resizable: true
    fullscreen: false
    vsync: true
    focused: true
    refreshRate: 60
engine_settings:
    api: OpenGL # OpenGL or Vulkan or DirectX11
    name: OpenGLEngine
resources:
    shaders:
        - name: Background_Texture
          path: Shaders/Background_Texture
        - name: Skybox
          path: Shaders/Skybox
        - name: Particle
          path: Shaders/Particle
        - name: Particle_Snow
          path: Shaders/Particle_Snow
        - name: Wireframe
          path: Shaders/Wireframe
        - name: Text2D
          path: Shaders/Text2D