config_name: DefaultConfig
version: 0.1a
window_settings:
    api: GLFW # GLFW or WIN32
    name: VenomEngine
    width: 1920
    height: 1080
    resizable: true
    fullscreen: false
    vsync: true
    focused: true
    refreshRate: 60
engine_settings:
    api: OpenGL # OpenGL or Vulkan or DirectX12
    name: OpenGLEngine
resources:
    shaders:
        - name: 3DObjectMarker
          path: Shaders/3DObjectMarker
        - name: Background_Texture
          path: Shaders/Background_Texture
        - name: Skybox
          path: Shaders/Skybox
        - name: Particle
          path: Shaders/Particle
        - name: Particle_Snow
          path: Shaders/Particle_Snow
        - name: Wireframe
          path: Shaders/Wireframe
        - name: Text2D
          path: Shaders/Text2D
        - name: Bezier
          path: Shaders/Bezier
        - name: Bezier_Wireframe
          path: [Shaders/Wireframe.frag, Shaders/Wireframe.vert, Shaders/Bezier.tcs, Shaders/Bezier.tes]
        - name: Normal_Shader
          path: Shaders/Normal_Shader
        - name: Lamp
          path: Shaders/Lamp
        - name: PBR_Shader
          path: Shaders/Material
    textures:
        - name: Snowflake
          path: Particles/Snow.png
        - name: Skybox_Texture
          type: CubeMap
          path: [Skybox/right.png, Skybox/left.png, Skybox/top.png, Skybox/bottom.png, Skybox/front.png, Skybox/back.png]
        - name: DesertSkybox_Texture
          type: CubeMap
          path: [DesertSkybox/right.png, DesertSkybox/left.png, DesertSkybox/top.png, DesertSkybox/bottom.png, DesertSkybox/front.png, DesertSkybox/back.png]
        - name: Earth
          path: Planets/earth.jpg
        - name: Moon
          path: Planets/moon.jpg
        - name: Sun
          path: Planets/sun.jpg
        - name: Mercury
          path: Planets/mercury.jpg
        - name: Venus
          path: Planets/venus.jpg
        - name: Mars
          path: Planets/mars.jpg
        - name: Jupiter
          path: Planets/jupiter.jpg
        - name: Saturn
          path: Planets/saturn.jpg
        - name: Uranus
          path: Planets/uranus.jpg
        - name: Neptune
          path: Planets/neptune.jpg
        - name: Shrek_Texture
          path: Shrek/Shrek_Body.png
        - name: Assignment5_Texture
          path: Assignment5/texture.png
    models:
        - name: Sphere
          path: Sphere
          radius: 1.0
          sectors: 32
          stacks: 32
        - name: Square
          path: Square
        - name: Eight
          path: Assignment1/eight.uniform.obj
        - name: Shrek_Model
          path: Shrek/Shrek.obj
        - name: Floppa_Model
          path: Floppa/flop.fbx
        - name: Assignment5_Model
          path: Assignment5/model.obj
        - name: Compass
          path: Compass/scene.gltf
        - name: Backpack
          path: Backpack/scene.gltf