config_name: DefaultConfig
version: 0.1a
window_settings:
    api: GLFW # GLFW or WIN32
    name: Homework1
    width: 1920
    height: 1080
    resizable: true
    fullscreen: false
    vsync: true
    focused: true
    refreshRate: 60
engine_settings:
    api: OpenGL # OpenGL or Vulkan or DirectX12
    name: OpenGLEngine
resources:
    shaders:
        - name: Background_Texture
          path: Shaders/Background_Texture
        - name: Skybox
          path: Shaders/Skybox
        - name: Particle
          path: Shaders/Particle
        - name: Particle_Snow
          path: Shaders/Particle_Snow
        - name: Wireframe
          path: Shaders/Wireframe
        - name: Text2D
          path: Shaders/Text2D
        - name: Bezier
          path: Shaders/Bezier
    textures:
        - name: Snowflake
          path: Particles/Snow.png
        - name: Skybox_Texture
          type: CubeMap
          path: [Skybox/right.png, Skybox/left.png, Skybox/top.png, Skybox/bottom.png, Skybox/front.png, Skybox/back.png]
        - name: Earth
          path: Planets/earth.jpg
        - name: Moon
          path: Planets/moon.jpg
        - name: Sun
          path: Planets/sun.jpg
        - name: Mercury
          path: Planets/mercury.jpg
        - name: Venus
          path: Planets/venus.jpg
        - name: Mars
          path: Planets/mars.jpg
        - name: Jupiter
          path: Planets/jupiter.jpg
        - name: Saturn
          path: Planets/saturn.jpg
        - name: Uranus
          path: Planets/uranus.jpg
        - name: Neptune
          path: Planets/neptune.jpg